# Generated by Django 3.0.7 on 2020-06-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200624_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesplace',
            options={'ordering': ('order',), 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',), 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='my_order',
        ),
        migrations.AddField(
            model_name='imagesplace',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
