# Generated by Django 3.0.7 on 2020-09-26 12:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200926_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesplace',
            options={'ordering': ('order',), 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',), 'verbose_name': 'Интересное место', 'verbose_name_plural': 'Интересные места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lat',
            field=models.FloatField(default=0, verbose_name='Координаты широты'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lng',
            field=models.FloatField(default=0, verbose_name='Координаты долготы'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Подробная информация'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
