# Generated by Django 3.0.7 on 2020-10-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20200926_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagesPlace',
            new_name='PlacesImages',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='detailed_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='coordinates_lat',
            new_name='latitude_coord',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='coordinates_lng',
            new_name='longitude_coord',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
