# Generated by Django 3.0.7 on 2020-10-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20201011_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesimages',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
